import type { Access, CollectionConfig } from 'payload'
import { denyKioskManager, hideForKioskManager } from '../access/kioskRoles'
import { setTenantFromUser } from '../hooks/setTenantFromUser'
import {
  schoolTenantCreate,
  schoolTenantWrite,
  teacherSessionsRead,
  roleOf,
} from '../access/schoolAccess'

/**
 * Teachers get their session scope on update; non-teachers route through
 * schoolTenantWrite (denies staff, which is correct — only admin roles may
 * mutate auto-generated sessions outside the teacher UI).
 */
const sessionUpdate: Access = async (args) =>
  roleOf(args.req.user) === 'teacher' ? teacherSessionsRead(args) : schoolTenantWrite(args)

/**
 * ClassSessions — one weekly meeting record per class, auto-generated by the
 * schedule engine. Teachers may read and update sessions for their own
 * classes (mark held/cancelled, add notes). Only admin roles may create or
 * delete sessions (idempotent generation is the primary create path).
 */
export const ClassSessions: CollectionConfig = {
  slug: 'class-sessions',
  labels: { singular: 'Session', plural: 'Sessions' },
  admin: {
    enableListViewSelectAPI: true,
    group: 'Sunday School',
    hidden: hideForKioskManager,
    useAsTitle: 'date',
    defaultColumns: ['class', 'date', 'status'],
    description: 'One weekly meeting of a class.',
  },
  access: {
    read: denyKioskManager(teacherSessionsRead),
    create: denyKioskManager(schoolTenantCreate),
    update: denyKioskManager(sessionUpdate),
    delete: denyKioskManager(schoolTenantWrite),
  },
  hooks: { beforeChange: [setTenantFromUser] },
  fields: [
    {
      name: 'tenant',
      type: 'relationship',
      relationTo: 'tenants',
      required: true,
      index: true,
      admin: { hidden: true },
    },
    { name: 'class', type: 'relationship', relationTo: 'school-classes', required: true, index: true },
    { name: 'date', type: 'date', required: true, index: true },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'scheduled',
      options: [
        { label: 'Scheduled', value: 'scheduled' },
        { label: 'Held', value: 'held' },
        { label: 'Cancelled', value: 'cancelled' },
      ],
    },
    { name: 'notes', type: 'textarea' },
  ],
  indexes: [{ fields: ['tenant', 'class', 'date'], unique: true }],
}

export default ClassSessions
