import type { CollectionConfig } from 'payload'
import { denyKioskManager } from '../access/kioskRoles'
import { setTenantFromUser } from '../hooks/setTenantFromUser'
import {
  readByRole,
  writeByRole,
  schoolAdminCreate,
  teacherSessionsResolve,
  schoolAdminSessionsRead,
} from '../access/schoolAccess'

/**
 * ClassSessions — one weekly meeting record per class, auto-generated by the
 * schedule engine. Teachers may read and update sessions for their own
 * classes (mark held/cancelled, add notes). Only admin roles may create or
 * delete sessions (idempotent generation is the primary create path).
 */
export const ClassSessions: CollectionConfig = {
  slug: 'class-sessions',
  labels: { singular: 'Session', plural: 'Sessions' },
  admin: {
    enableListViewSelectAPI: true,
    group: 'Programs',
    hidden: true,
    useAsTitle: 'date',
    defaultColumns: ['class', 'date', 'status'],
    description: 'One weekly meeting of a class.',
  },
  access: {
    read: denyKioskManager(readByRole({ teacher: teacherSessionsResolve, schoolAdmin: schoolAdminSessionsRead })),
    create: denyKioskManager(schoolAdminCreate),
    update: denyKioskManager(writeByRole({ teacher: teacherSessionsResolve, schoolAdmin: schoolAdminSessionsRead })),
    delete: denyKioskManager(writeByRole({ schoolAdmin: schoolAdminSessionsRead })),
  },
  hooks: { beforeChange: [setTenantFromUser] },
  fields: [
    {
      name: 'tenant',
      type: 'relationship',
      relationTo: 'tenants',
      required: true,
      index: true,
      admin: { hidden: true },
    },
    { name: 'class', type: 'relationship', relationTo: 'school-classes', required: true, index: true },
    { name: 'date', type: 'date', required: true, index: true },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'scheduled',
      options: [
        { label: 'Scheduled', value: 'scheduled' },
        { label: 'Held', value: 'held' },
        { label: 'Cancelled', value: 'cancelled' },
      ],
    },
    { name: 'notes', type: 'textarea' },
  ],
  indexes: [{ fields: ['tenant', 'class', 'date'], unique: true }],
}

export default ClassSessions
