/**
 * Custom admin login route.
 *
 * Payload 3.39 does not expose `admin.components.views.login` as an override
 * hook — `oneSegmentViews.login` is hard-coded to Payload's built-in view.
 * To cleanly replace the login UI we mount our own Next.js route here.
 * A file-system route at `/admin/login` takes precedence over Payload's
 * `[[...segments]]` catch-all, so this page wins for the login URL while
 * every other `/admin/*` path still flows through Payload's admin shell.
 *
 * This file is owned by the app (not generated by Payload), which is why
 * it lives here as a tiny wrapper around `src/admin/LoginView`.
 */

import type { Metadata } from 'next'

import LoginView from '@/admin/LoginView'

export const metadata: Metadata = {
  title: 'Sign in — OpenMasjid',
  description: 'Sign in to manage your masjid',
}

export default function Page() {
  return <LoginView />
}
