/**
 * One-shot importer: pulls active carousel slides from the legacy
 * https://api.masjidkiosk.io kiosk API and creates equivalent
 * CarouselSlides (+ QRCodes / Media as needed) in the local Payload DB.
 *
 * Idempotent: re-running matches existing slides by title + tenant and
 * upserts. Run with: `node --env-file=.env --import tsx scripts/importKioskCarousel.ts`
 */

import { getPayload } from 'payload'
import config from '@payload-config'

const KIOSK_API = 'https://api.masjidkiosk.io'
const TENANT_SLUG = 'icp' // ICP is the destination tenant

type LegacyQrCode = {
  id: string
  url: string
  label: string | null
  image_url: string | null
  foreground_color: string | null
  background_color: string | null
}

type LegacySlide = {
  id: string
  title: string
  details1: string | null
  details2: string | null
  qr_code_url: string | null // legacy: a raw image (event flyer etc), not a QR-library entry
  is_active: boolean
  show_on_carousel: boolean
  priority: number
  display_duration: number
  start_date: string | null
  end_date: string | null
  prayer_timings_enabled: boolean
  background_theme: string | null
  qr_code: LegacyQrCode | null
}

async function fetchSlides(): Promise<LegacySlide[]> {
  const res = await fetch(`${KIOSK_API}/api/carousel-slides?active=true&showOnCarousel=true`)
  if (!res.ok) throw new Error(`kiosk API ${res.status}`)
  const json: { slides: LegacySlide[] } = await res.json()
  return json.slides
}

async function fetchImage(url: string): Promise<Buffer> {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`image fetch ${res.status} for ${url}`)
  const ab = await res.arrayBuffer()
  return Buffer.from(ab)
}

async function main() {
  const payload = await getPayload({ config })
  const req: any = { user: { id: 0, role: 'platformOwner', email: 'kiosk-import@seed' } }

  // Resolve ICP tenant
  const tenants = await payload.find({
    collection: 'tenants',
    where: { slug: { equals: TENANT_SLUG } },
    limit: 1,
    overrideAccess: true,
    req,
  })
  const tenant = tenants.docs[0]
  if (!tenant) throw new Error(`tenant '${TENANT_SLUG}' not found`)
  const tenantId = tenant.id
  console.log(`✓ Resolved tenant ${tenant.name} (id=${tenantId})`)

  const slides = await fetchSlides()
  console.log(`✓ Fetched ${slides.length} active carousel slides from production`)

  for (const slide of slides) {
    console.log(`\n→ Importing "${slide.title}"`)

    // 1. Maybe upsert a QR code (only for QR-library-linked slides)
    let qrCodeId: string | number | null = null
    if (slide.qr_code) {
      const qr = slide.qr_code
      const existing = await payload.find({
        collection: 'qr-codes',
        where: {
          and: [
            { tenant: { equals: tenantId } },
            { targetUrl: { equals: qr.url } },
          ],
        },
        limit: 1,
        overrideAccess: true,
        req,
      })
      if (existing.docs[0]) {
        qrCodeId = existing.docs[0].id
        console.log(`  · qr-code (reused #${qrCodeId})`)
      } else {
        const created = await payload.create({
          collection: 'qr-codes',
          data: {
            label: qr.label || `Imported QR ${qr.id.slice(0, 6)}`,
            targetUrl: qr.url,
            fgColor: qr.foreground_color || '#000000',
            bgColor: qr.background_color || '#FFFFFF',
            tenant: tenantId,
          },
          overrideAccess: true,
          req,
        })
        qrCodeId = created.id
        console.log(`  · qr-code created (#${qrCodeId}) — PNG generated by hook`)
      }
    }

    // 2. Maybe download + upload the legacy event-flyer image
    let imageId: string | number | null = null
    if (slide.qr_code_url && !slide.qr_code) {
      const imgUrl = slide.qr_code_url.startsWith('http')
        ? slide.qr_code_url
        : `${KIOSK_API}${slide.qr_code_url}`
      try {
        const buf = await fetchImage(imgUrl)
        const filename = `kiosk-import-${slide.id.slice(0, 8)}.png`
        const media = await payload.create({
          collection: 'media',
          data: { alt: slide.title, tenant: tenantId },
          file: { data: buf, mimetype: 'image/png', name: filename, size: buf.length },
          overrideAccess: true,
          req,
        })
        imageId = media.id
        console.log(`  · image uploaded (#${imageId}, ${buf.length} bytes)`)
      } catch (err) {
        console.warn(`  ! image fetch failed: ${(err as Error).message} — continuing without image`)
      }
    }

    // 3. Upsert the carousel slide
    const existingSlide = await payload.find({
      collection: 'carousel-slides',
      where: {
        and: [
          { tenant: { equals: tenantId } },
          { title: { equals: slide.title } },
        ],
      },
      limit: 1,
      overrideAccess: true,
      req,
    })

    const data: any = {
      title: slide.title,
      details1: slide.details1,
      details2: slide.details2,
      backgroundTheme: slide.background_theme || 'clean',
      prayerTimingsEnabled: !!slide.prayer_timings_enabled,
      displayDurationMs: Math.max(5000, Math.min(60000, slide.display_duration || 10000)),
      priority: Math.max(0, Math.min(10, slide.priority ?? 5)),
      active: !!slide.is_active,
      startDate: slide.start_date,
      endDate: slide.end_date,
      showInCarousel: !!slide.show_on_carousel,
      tenant: tenantId,
    }
    if (qrCodeId !== null) data.qrCode = qrCodeId
    if (imageId !== null) data.image = imageId

    if (existingSlide.docs[0]) {
      await payload.update({
        collection: 'carousel-slides',
        id: existingSlide.docs[0].id,
        data,
        overrideAccess: true,
        req,
      })
      console.log(`  · slide updated (#${existingSlide.docs[0].id})`)
    } else {
      const created = await payload.create({
        collection: 'carousel-slides',
        data,
        overrideAccess: true,
        req,
      })
      console.log(`  · slide created (#${created.id})`)
    }
  }

  console.log(`\n✓ Import complete (${slides.length} slides)`)
  process.exit(0)
}

main().catch((err) => {
  console.error('Import failed:', err)
  process.exit(1)
})
