/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'prayer-schedules': PrayerSchedule;
    events: Event;
    'hero-slides': HeroSlide;
    announcements: Announcement;
    services: Service;
    pages: Page;
    forms: Form;
    'form-submissions': FormSubmission;
    'donation-funds': DonationFund;
    donations: Donation;
    'membership-tiers': MembershipTier;
    members: Member;
    media: Media;
    users: User;
    tenants: Tenant;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'prayer-schedules': PrayerSchedulesSelect<false> | PrayerSchedulesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'hero-slides': HeroSlidesSelect<false> | HeroSlidesSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'donation-funds': DonationFundsSelect<false> | DonationFundsSelect<true>;
    donations: DonationsSelect<false> | DonationsSelect<true>;
    'membership-tiers': MembershipTiersSelect<false> | MembershipTiersSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Prayer schedules cover a date range. Set the range + iqamah rules, then click "Generate times" to compute adhan times per day from the tenant’s location. Before any schedule’s start date has been reached, the public site shows "Prayer times coming soon".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-schedules".
 */
export interface PrayerSchedule {
  id: number;
  /**
   * e.g. "Summer 2026", "Ramadan 2026", "Winter".
   */
  name: string;
  /**
   * First day this schedule covers.
   */
  startDate: string;
  /**
   * Last day this schedule covers. "Generate times" builds one day-row per date in this range.
   */
  endDate: string;
  /**
   * Bulk iqamah for every day in the range. Each prayer is either an absolute time or an offset from the computed adhan. Maghrib is usually an offset (e.g. "+5 min after sunset"); others are usually absolute. Click "Apply iqamah to range" after changing these to rewrite all days.
   */
  iqamahRules: {
    fajr: {
      mode: 'absolute' | 'offset';
      absoluteValue?: string | null;
      offsetMinutes?: number | null;
    };
    zuhr: {
      mode: 'absolute' | 'offset';
      absoluteValue?: string | null;
      offsetMinutes?: number | null;
    };
    asr: {
      mode: 'absolute' | 'offset';
      absoluteValue?: string | null;
      offsetMinutes?: number | null;
    };
    maghrib: {
      mode: 'absolute' | 'offset';
      absoluteValue?: string | null;
      offsetMinutes?: number | null;
    };
    isha: {
      mode: 'absolute' | 'offset';
      absoluteValue?: string | null;
      offsetMinutes?: number | null;
    };
  };
  /**
   * Absolute times for Friday Jummah (e.g. 12:45 PM, 1:30 PM, 2:15 PM). Replaces Zuhr iqamah on Fridays on the public site.
   */
  jummahTimes?:
    | {
        time: string;
        id?: string | null;
      }[]
    | null;
  /**
   * One row per date in the range. Auto-filled on save when the range or iqamah rules change. Edit an individual row for per-day overrides; changing the range or rules will overwrite those edits on the next save.
   */
  days?:
    | {
        date: string;
        /**
         * Fajr must be prayed before sunrise. Informational — not shown on the public site by default.
         */
        sunrise?: string | null;
        fajr?: {
          adhan?: string | null;
          iqamah?: string | null;
        };
        zuhr?: {
          adhan?: string | null;
          iqamah?: string | null;
        };
        asr?: {
          adhan?: string | null;
          iqamah?: string | null;
        };
        maghrib?: {
          adhan?: string | null;
          iqamah?: string | null;
        };
        isha?: {
          adhan?: string | null;
          iqamah?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Optional, e.g. "Taraweeh after Isha".
   */
  notes?: string | null;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * A tenant is a masjid (or umbrella org) served by the platform. Each tenant has its own domain, branding, and content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * Public-facing name shown in the site header, footer, and emails, e.g. "Islamic Center of Prosper".
   */
  name: string;
  /**
   * Short identifier used for the platform subdomain (e.g. "icp" becomes icp.openmasjid.app). Lowercase letters, numbers, and dashes only. Avoid changing after launch.
   */
  slug: string;
  /**
   * Choose "Masjid" for a single-community site, or "Umbrella Organization" for a parent org that groups multiple masajid.
   */
  siteType: 'masjid' | 'umbrella';
  /**
   * Add each custom domain the masjid owns (both with and without www if applicable). Visitors reaching these domains will see this tenant's public site.
   */
  customDomains?:
    | {
        /**
         * Hostname only — no https:// and no trailing slash. Example: icprosper.org
         */
        domain: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Upload a logo and set brand colors. Hover/pressed/soft shades are derived automatically — you only choose three colors.
   */
  branding?: {
    /**
     * Primary logo shown in the site header and admin panel. Prefer a transparent PNG or SVG.
     */
    logo?: (number | null) | Media;
    /**
     * Square icon shown in the browser tab for both the public site and the admin panel. 32×32 or 64×64 PNG/ICO — NOT the full logo. If left blank, a neutral OpenMasjid icon is used.
     */
    favicon?: (number | null) | Media;
    /**
     * Main brand color — used for buttons, links, and headings. Hex value, e.g. #0F1E4A (navy).
     */
    primaryColor?: string | null;
    /**
     * Supporting accent — used in highlights and secondary UI. Hex value, e.g. #28A0B4 (teal).
     */
    secondaryColor?: string | null;
    /**
     * Warm accent — used sparingly on badges and devotional elements. Hex value, e.g. #F0C88C (gold).
     */
    accentColor?: string | null;
    /**
     * Headline font. Body text and Arabic fonts are fixed platform-wide for consistency.
     */
    displayFont?: ('Fraunces' | 'Playfair Display' | 'DM Serif Display' | 'IBM Plex Sans') | null;
  };
  /**
   * Masjid coordinates and timezone. Lat/lng are auto-filled from the address on save. Override manually if the geocoder picks the wrong point.
   */
  location?: {
    /**
     * Decimal degrees (e.g. 33.2257 for Prosper, TX).
     */
    lat?: number | null;
    /**
     * Decimal degrees (e.g. -96.7969 for Prosper, TX).
     */
    lng?: number | null;
    /**
     * IANA timezone for the masjid (e.g. America/Chicago, America/New_York). See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
     */
    timezone?: string | null;
  };
  /**
   * Select the calculation convention your community follows. ISNA is the default in North America.
   */
  prayerCalc?: {
    method?: ('ISNA' | 'MWL' | 'Egyptian' | 'UmmAlQura' | 'Karachi' | 'Tehran' | 'Jafari') | null;
    asrMadhab?: ('Standard' | 'Hanafi') | null;
  };
  /**
   * Shown in the site footer and the About page.
   */
  contactInfo?: {
    phone?: string | null;
    email?: string | null;
    /**
     * Street address, one line per part (street, city/state/zip).
     */
    address?: string | null;
  };
  /**
   * Links to the masjid's social accounts. Rendered as icons in the footer.
   */
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'youtube' | 'twitter' | 'linkedin';
        /**
         * Full URL including https://
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional short phrase shown beneath the logo in the footer, e.g. "Serving Prosper since 2010".
   */
  footerTagline?: string | null;
  /**
   * A tenant is "pending" until its admin user signs in for the first time. Pending tenants are subject to auto-cleanup after 7 days.
   */
  status?: ('pending' | 'trialing' | 'active' | 'past_due' | 'canceled' | 'offline' | 'grandfathered') | null;
  /**
   * Recorded at signup (now + 14 days). Not enforced yet — billing/paywall will read this when introduced.
   */
  trialEndsAt?: string | null;
  /**
   * Free-form blob captured at public signup (role, migration source, etc.). Used for analytics, not for product logic.
   */
  signupMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  subscriptionPlan?: ('monthly' | 'annual' | 'grandfathered') | null;
  stripeCustomerId?: string | null;
  stripeSubscriptionId?: string | null;
  currentPeriodEnd?: string | null;
  /**
   * Set when entering past_due (from trial) or canceled. Public site goes offline after this date.
   */
  gracePeriodEndsAt?: string | null;
  /**
   * Choose how the "Donate" button behaves. Start with an external link; Stripe integration is planned for a future release.
   */
  donationConfig?: {
    /**
     * External link is the default. Switch to Stripe Connect after connecting your account.
     */
    mode?: ('external' | 'connect') | null;
    /**
     * Shown only when Donation Mode is "External link". Full URL to your existing donation page.
     */
    externalUrl?: string | null;
    /**
     * Connected Stripe account ID. Set automatically by the Connect OAuth flow.
     */
    stripeAccountId?: string | null;
    stripeAccountConnectedAt?: string | null;
    stripeChargesEnabled?: boolean | null;
    stripePayoutsEnabled?: boolean | null;
    stripeAccountLastSyncedAt?: string | null;
  };
  /**
   * Per-milestone state for the post-login setup wizard. Auto-detected milestones are not stored here; only explicit user actions (skip, mark-complete) are persisted.
   */
  onboarding?: {
    /**
     * Explicit user action for the branding milestone.
     */
    branding?: ('complete' | 'dismissed') | null;
    /**
     * Explicit user action for the identity milestone.
     */
    identity?: ('complete' | 'dismissed') | null;
    /**
     * Explicit user action for the prayer milestone.
     */
    prayer?: ('complete' | 'dismissed') | null;
    /**
     * Explicit user action for the firstEvent milestone.
     */
    firstEvent?: ('complete' | 'dismissed') | null;
    /**
     * Explicit user action for the hero milestone.
     */
    hero?: ('complete' | 'dismissed') | null;
    /**
     * Explicit user action for the donations milestone.
     */
    donations?: ('complete' | 'dismissed') | null;
  };
  /**
   * Set when the user dismisses the celebratory screen.
   */
  onboardingCompletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Uploaded images and PDFs (event flyers, logos, hero photos). Files live in this tenant's library only — other masajid cannot see them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image in one short sentence for screen readers and SEO. Strongly recommended on every upload — leave blank only for purely decorative images.
   */
  alt?: string | null;
  /**
   * Automatically set from your account for non-platform users. Only a Platform Owner can reassign media across tenants.
   */
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    favicon?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Classes, programs, and gatherings. Published events appear on the public Events page; featured events also appear in the homepage hero.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * The event name as it appears in cards and detail pages.
   */
  title: string;
  /**
   * One or two sentences shown on event cards and in the hero. Keep it under ~160 characters.
   */
  shortDescription?: string | null;
  /**
   * The full body of the event detail page. Supports formatting, links, and lists.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * A single primary category. Used for filtering on the Events page and for the colored tag on cards.
   */
  tag?: ('weekly-class' | 'ramadan' | 'eid' | 'sisters' | 'youth' | 'brothers' | 'community') | null;
  /**
   * Who this event is for — visitors filter by audience. Choose multiple when the event welcomes more than one group.
   */
  audience?: ('families' | 'sisters' | 'youth' | 'brothers' | 'all')[] | null;
  /**
   * Free-text cadence for recurring events, e.g. "Mondays after Isha" or "Every Saturday, 10 AM".
   */
  when?: string | null;
  /**
   * Used for sorting and for hiding past events. Leave blank for always-on recurring classes.
   */
  startDate?: string | null;
  /**
   * Optional — used when an event spans multiple days.
   */
  endDate?: string | null;
  /**
   * Where inside/around the masjid the event takes place.
   */
  location?: string | null;
  /**
   * Optional — only needed when the event is at a different address than the masjid.
   */
  address?: string | null;
  /**
   * Optional — shown on the event detail page for attendee questions.
   */
  contact?: string | null;
  /**
   * Choose how this event renders on the Events page. "Image" uses your uploaded flyer; "Template" auto-generates a branded flyer from the title; "Text only" is a compact card.
   */
  displayMode: 'image' | 'template' | 'text';
  /**
   * Shown only when Display Mode is "Image". Upload a ready-made flyer (ideally portrait orientation).
   */
  flyerImage?: (number | null) | Media;
  /**
   * Shown only when Display Mode is "Template". Pick the color scheme for the auto-generated flyer.
   */
  templateVariant?: ('default' | 'navy' | 'gold') | null;
  /**
   * Tick to include this event in the homepage hero slider. Featured events rotate alongside hero slides.
   */
  featured?: boolean | null;
  /**
   * Shown only when "Featured on Homepage" is on. Picks the theme for this event's slide in the hero.
   */
  heroAccent?: ('cream' | 'teal' | 'navy' | 'gold') | null;
  /**
   * Auto-generated from the title (e.g. "evidences-of-islam"). Edit only if you need a custom URL.
   */
  slug?: string | null;
  /**
   * Set automatically from your account. Only a Platform Owner can reassign.
   */
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Slides for the homepage hero slider. Use these for mission statements, donation pushes, or general announcements. Featured events from the Events collection are auto-added at render time.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides".
 */
export interface HeroSlide {
  id: number;
  /**
   * Small label above the headline, e.g. "Islamic Center of Prosper". Optional — omit to save vertical space.
   */
  eyebrow?: string | null;
  /**
   * The main line visitors see. Short and action-oriented.
   */
  title: string;
  /**
   * One or two sentences supporting the headline.
   */
  body?: string | null;
  /**
   * Optional small line below the CTAs, e.g. "Monthly recurring available".
   */
  meta?: string | null;
  /**
   * Visual layout for this slide. Each style has a built-in color treatment that you can override via Slide Theme below.
   */
  style: 'original' | 'split' | 'live' | 'photo';
  accent: 'cream' | 'teal' | 'navy' | 'gold';
  /**
   * Content shown in the right-side card stack for the Split layout. Only used when Layout Style is "Split".
   */
  splitFields?: {
    /**
     * Caption shown over the photo card. e.g. "Friday gathering".
     */
    photoLabel?: string | null;
    /**
     * Tint for the placeholder when no image is uploaded. Brand / Secondary / Accent pull from your tenant theme; Custom lets you pick a one-off color.
     */
    photoTone?: ('brand' | 'secondary' | 'accent' | 'custom') | null;
    customColor?: string | null;
    /**
     * Eyebrow above the photo card title. e.g. "Jummah · this week".
     */
    cardTag?: string | null;
    /**
     * Main line on the photo card. e.g. "On Tawakkul — Shaykh Omar".
     */
    cardTitle?: string | null;
    /**
     * Real photo for the card. Falls back to a tinted placeholder if empty.
     */
    image?: (number | null) | Media;
  };
  /**
   * Background image and ayah card content for the full-bleed Photo layout. Only used when Layout Style is "Photo".
   */
  photoFields?: {
    /**
     * Caption corner-tag for the background. e.g. "Masjid prayer hall · golden hour".
     */
    photoLabel?: string | null;
    /**
     * Tint for the background placeholder when no image is uploaded. Brand / Secondary / Accent pull from your tenant theme; Custom lets you pick a one-off color.
     */
    photoTone?: ('brand' | 'secondary' | 'accent' | 'custom') | null;
    customColor?: string | null;
    /**
     * Decorative pattern shown when no Background Photo is uploaded.
     */
    photoPattern?: ('arch' | 'geometric' | 'stars' | 'lattice') | null;
    /**
     * Full-bleed photo. Falls back to a tinted placeholder if empty.
     */
    image?: (number | null) | Media;
    /**
     * Right-to-left Arabic verse displayed in the side card.
     */
    ayahArabic?: string | null;
    /**
     * Translation displayed below the Arabic.
     */
    ayahTranslation?: string | null;
    /**
     * Reference for the verse, e.g. "An-Nisa · 4:103".
     */
    ayahCitation?: string | null;
  };
  /**
   * Up to two buttons per slide. Mark one as Primary (filled) and leave the other secondary (outlined).
   */
  ctas?:
    | {
        label: string;
        /**
         * Use "Internal page" for site pages (faster, handles branding). Use "External URL" for LaunchGood, forms, etc.
         */
        linkType: 'page' | 'url';
        /**
         * Shown only when Link Type is "Internal page".
         */
        page?: ('/' | '/events' | '/prayer-times' | '/donate' | '/about') | null;
        /**
         * Shown only when Link Type is "External URL". Include https://
         */
        url?: string | null;
        /**
         * Optional. Pick an icon for the button.
         */
        icon?: string | null;
        /**
         * On = filled/branded button. Off = outlined secondary button. Mark one CTA per slide as primary.
         */
        primary?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers appear first in the slider.
   */
  sortOrder?: number | null;
  /**
   * Uncheck to hide this slide without deleting it.
   */
  active?: boolean | null;
  /**
   * Set automatically from your account. Only a Platform Owner can reassign.
   */
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Short-lived notices shown at the top of the public site (closures, schedule changes, reminders). Use Events for programs; use Announcements for quick updates.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  /**
   * A short headline, e.g. "Jumu'ah moved to 1:30 PM this week".
   */
  title: string;
  /**
   * Supporting detail shown when the announcement is expanded.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * High priority renders with stronger visual emphasis (e.g. bolder banner). Use sparingly.
   */
  priority?: ('normal' | 'high') | null;
  /**
   * Manual on/off switch. Turn off to hide immediately. Prefer this for "show, then hide on my schedule"; use Expires At for automatic hiding.
   */
  active?: boolean | null;
  /**
   * Optional automatic hide date. Once past this date, the announcement stops rendering even if Active is on. Leave blank for evergreen notices.
   */
  expiresAt?: string | null;
  /**
   * Set automatically from your account. Only a Platform Owner can reassign.
   */
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Ongoing services the masjid offers (counseling, new-Muslim support, funeral services, etc.). These appear as icon cards on the homepage Services grid.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * The service name, e.g. "New Muslims (Ansar)" or "Funeral Services".
   */
  title: string;
  /**
   * A short sentence or two explaining what this service offers.
   */
  description?: string | null;
  /**
   * Pick an icon that represents this service.
   */
  icon: string;
  /**
   * Lower numbers appear first in the grid.
   */
  sortOrder?: number | null;
  /**
   * Set automatically from your account. Only a Platform Owner can reassign.
   */
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Static content pages (About, Our Story, Bylaws, etc.). Each page becomes a URL under the tenant's site. Use the built-in pages (Home, Events, Prayer Times, Donate) for standard sections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Shown as the page heading and in the browser tab.
   */
  title: string;
  /**
   * Auto-generated from the title. Becomes the URL path, e.g. "about" renders at /about. Lowercase letters, numbers, and dashes only.
   */
  slug?: string | null;
  /**
   * The body of the page. Supports headings, lists, links, and inline images.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * When enabled, this page appears as a link in the public site header navigation. Only published pages are shown.
   */
  showInNav?: boolean | null;
  /**
   * Lower numbers appear first. Pages with the same order (or no order) are sorted alphabetically by title.
   */
  navOrder?: number | null;
  /**
   * Set automatically from your account. Only a Platform Owner can reassign.
   */
  tenant?: (number | null) | Tenant;
  /**
   * Optional overrides for search engine and social-share previews. Leave blank to use sensible defaults derived from the page.
   */
  seo?: {
    /**
     * Overrides the page title in the browser tab and social shares. ~60 chars max.
     */
    title?: string | null;
    /**
     * Used for the meta description and social share previews. ~155 chars max.
     */
    description?: string | null;
    /**
     * Overrides the default share image (tenant logo). Recommended 1200×630.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  /**
   * URL slug. /forms/<slug>.
   */
  slug?: string | null;
  status: 'draft' | 'published' | 'closed';
  /**
   * Shown above the form on the public page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The form definition. Use the builder above.
   */
  schema:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  settings?: {
    submitButtonLabel?: string | null;
    successMessage?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Max submissions before the form closes. Leave blank for no limit.
     */
    capacity?: number | null;
    closedMessage?: string | null;
    notificationEmails?:
      | {
          email: string;
          id?: string | null;
        }[]
      | null;
    sendConfirmation?: boolean | null;
    confirmationSubject?: string | null;
    /**
     * Plain text body. {{name}} interpolates the submitter name field if present.
     */
    confirmationBody?: string | null;
  };
  payment?: {
    enabled?: boolean | null;
    mode?: ('fixed' | 'suggested') | null;
    priceCents?: number | null;
    suggestedAmountsCents?:
      | {
          amount: number;
          id?: string | null;
        }[]
      | null;
    allowCustomAmount?: boolean | null;
    currency?: ('usd' | 'cad' | 'gbp') | null;
    /**
     * Shown on the Stripe checkout page.
     */
    description?: string | null;
  };
  tenant: number | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Form submissions. Read-only — created by the public submit endpoint.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  tenant: number | Tenant;
  form: number | Form;
  submitterEmail?: string | null;
  submitterName?: string | null;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'new' | 'reviewed' | 'archived';
  paymentStatus?: ('na' | 'pending_payment' | 'paid' | 'expired') | null;
  amountCents?: number | null;
  currency?: string | null;
  stripeCheckoutSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  paidAt?: string | null;
  submittedAt: string;
  userAgent?: string | null;
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Categories donors can give toward (Sadaqah, Zakat, Building Fund, etc.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-funds".
 */
export interface DonationFund {
  id: number;
  tenant: number | Tenant;
  /**
   * Public-facing fund name (e.g. "Sadaqah", "Zakat", "Building Fund").
   */
  name: string;
  /**
   * URL-safe identifier, unique within this tenant.
   */
  slug: string;
  /**
   * Optional description shown beneath the fund name on the donate page.
   */
  description?: string | null;
  /**
   * Mark true for funds that accept Zakat (restricted use).
   */
  zakatEligible?: boolean | null;
  /**
   * Suggested donation chips (e.g. 25, 50, 100, 250). Optional.
   */
  suggestedAmounts?:
    | {
        /**
         * Whole-dollar amount shown as a quick-pick.
         */
        amount: number;
        id?: string | null;
      }[]
    | null;
  sortOrder?: number | null;
  /**
   * Inactive funds are hidden from the public donate page.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Aggregate donation records. No donor PII is stored — donor identity lives in Stripe.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations".
 */
export interface Donation {
  id: number;
  tenant: number | Tenant;
  fund: number | DonationFund;
  /**
   * Stored in cents; rendered as currency in list and detail views.
   */
  amount: number;
  currency?: string | null;
  frequency: 'one_time' | 'monthly';
  status: 'succeeded' | 'refunded' | 'failed';
  stripePaymentIntentId: string;
  stripeChargeId?: string | null;
  stripeSubscriptionId?: string | null;
  stripeAccountId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Paid recurring tiers congregants can subscribe to.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-tiers".
 */
export interface MembershipTier {
  id: number;
  tenant: number | Tenant;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  amountCents: number;
  /**
   * Dollars per period. Example: enter 25 for $25 / month. Enter 0 for a free tier (no Stripe billing — congregants sign up with name + email).
   */
  amount: number;
  cadence: 'monthly' | 'yearly';
  /**
   * Uncheck to soft-delete: hides from /membership but keeps existing subscribers billed.
   */
  active?: boolean | null;
  /**
   * Lower numbers appear first on the public page.
   */
  sortOrder?: number | null;
  stripeProductId?: string | null;
  stripePriceId?: string | null;
  archivedPriceIds?:
    | {
        priceId?: string | null;
        id?: string | null;
      }[]
    | null;
  lastStripeSyncAt?: string | null;
  lastStripeSyncError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Congregants subscribed to a membership tier.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  tenant: number | Tenant;
  email: string;
  name: string;
  phone?: string | null;
  tier: number | MembershipTier;
  status: 'active' | 'grace' | 'inactive';
  stripeCustomerId?: string | null;
  stripeSubscriptionId?: string | null;
  stripeSubscriptionStatus?: string | null;
  joinedAt?: string | null;
  currentPeriodEnd?: string | null;
  canceledAt?: string | null;
  /**
   * Admin-only notes; not visible to the member.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can log into the admin panel. Each non-platform user belongs to exactly one tenant and only sees that tenant's content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * First name, used for greetings and displayed in the admin panel
   */
  firstName: string;
  /**
   * Last name
   */
  lastName: string;
  /**
   * Platform Owner manages every masjid and the platform itself. Admin can change settings, branding, and users within one masjid. Staff can add/edit content (events, prayer times, announcements) but cannot change settings or manage users.
   */
  role: 'platformOwner' | 'admin' | 'staff';
  /**
   * Which masjid this user belongs to. Required for Admin and Staff; leave blank for Platform Owner (they access every tenant). Only a Platform Owner can change this field.
   */
  tenant?: (number | null) | Tenant;
  /**
   * Set the first time this user sees the onboarding welcome dialog. Used to suppress re-showing it on subsequent logins.
   */
  onboardingWelcomeSeenAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'prayer-schedules';
        value: number | PrayerSchedule;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'hero-slides';
        value: number | HeroSlide;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'donation-funds';
        value: number | DonationFund;
      } | null)
    | ({
        relationTo: 'donations';
        value: number | Donation;
      } | null)
    | ({
        relationTo: 'membership-tiers';
        value: number | MembershipTier;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-schedules_select".
 */
export interface PrayerSchedulesSelect<T extends boolean = true> {
  name?: T;
  startDate?: T;
  endDate?: T;
  iqamahRules?:
    | T
    | {
        fajr?:
          | T
          | {
              mode?: T;
              absoluteValue?: T;
              offsetMinutes?: T;
            };
        zuhr?:
          | T
          | {
              mode?: T;
              absoluteValue?: T;
              offsetMinutes?: T;
            };
        asr?:
          | T
          | {
              mode?: T;
              absoluteValue?: T;
              offsetMinutes?: T;
            };
        maghrib?:
          | T
          | {
              mode?: T;
              absoluteValue?: T;
              offsetMinutes?: T;
            };
        isha?:
          | T
          | {
              mode?: T;
              absoluteValue?: T;
              offsetMinutes?: T;
            };
      };
  jummahTimes?:
    | T
    | {
        time?: T;
        id?: T;
      };
  days?:
    | T
    | {
        date?: T;
        sunrise?: T;
        fajr?:
          | T
          | {
              adhan?: T;
              iqamah?: T;
            };
        zuhr?:
          | T
          | {
              adhan?: T;
              iqamah?: T;
            };
        asr?:
          | T
          | {
              adhan?: T;
              iqamah?: T;
            };
        maghrib?:
          | T
          | {
              adhan?: T;
              iqamah?: T;
            };
        isha?:
          | T
          | {
              adhan?: T;
              iqamah?: T;
            };
        id?: T;
      };
  notes?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  description?: T;
  tag?: T;
  audience?: T;
  when?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  address?: T;
  contact?: T;
  displayMode?: T;
  flyerImage?: T;
  templateVariant?: T;
  featured?: T;
  heroAccent?: T;
  slug?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  body?: T;
  meta?: T;
  style?: T;
  accent?: T;
  splitFields?:
    | T
    | {
        photoLabel?: T;
        photoTone?: T;
        customColor?: T;
        cardTag?: T;
        cardTitle?: T;
        image?: T;
      };
  photoFields?:
    | T
    | {
        photoLabel?: T;
        photoTone?: T;
        customColor?: T;
        photoPattern?: T;
        image?: T;
        ayahArabic?: T;
        ayahTranslation?: T;
        ayahCitation?: T;
      };
  ctas?:
    | T
    | {
        label?: T;
        linkType?: T;
        page?: T;
        url?: T;
        icon?: T;
        primary?: T;
        id?: T;
      };
  sortOrder?: T;
  active?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  priority?: T;
  active?: T;
  expiresAt?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  sortOrder?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  showInNav?: T;
  navOrder?: T;
  tenant?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  description?: T;
  schema?: T;
  settings?:
    | T
    | {
        submitButtonLabel?: T;
        successMessage?: T;
        capacity?: T;
        closedMessage?: T;
        notificationEmails?:
          | T
          | {
              email?: T;
              id?: T;
            };
        sendConfirmation?: T;
        confirmationSubject?: T;
        confirmationBody?: T;
      };
  payment?:
    | T
    | {
        enabled?: T;
        mode?: T;
        priceCents?: T;
        suggestedAmountsCents?:
          | T
          | {
              amount?: T;
              id?: T;
            };
        allowCustomAmount?: T;
        currency?: T;
        description?: T;
      };
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  tenant?: T;
  form?: T;
  submitterEmail?: T;
  submitterName?: T;
  data?: T;
  status?: T;
  paymentStatus?: T;
  amountCents?: T;
  currency?: T;
  stripeCheckoutSessionId?: T;
  stripePaymentIntentId?: T;
  paidAt?: T;
  submittedAt?: T;
  userAgent?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-funds_select".
 */
export interface DonationFundsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  description?: T;
  zakatEligible?: T;
  suggestedAmounts?:
    | T
    | {
        amount?: T;
        id?: T;
      };
  sortOrder?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations_select".
 */
export interface DonationsSelect<T extends boolean = true> {
  tenant?: T;
  fund?: T;
  amount?: T;
  currency?: T;
  frequency?: T;
  status?: T;
  stripePaymentIntentId?: T;
  stripeChargeId?: T;
  stripeSubscriptionId?: T;
  stripeAccountId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-tiers_select".
 */
export interface MembershipTiersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  description?: T;
  amountCents?: T;
  amount?: T;
  cadence?: T;
  active?: T;
  sortOrder?: T;
  stripeProductId?: T;
  stripePriceId?: T;
  archivedPriceIds?:
    | T
    | {
        priceId?: T;
        id?: T;
      };
  lastStripeSyncAt?: T;
  lastStripeSyncError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  tenant?: T;
  email?: T;
  name?: T;
  phone?: T;
  tier?: T;
  status?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  stripeSubscriptionStatus?: T;
  joinedAt?: T;
  currentPeriodEnd?: T;
  canceledAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        favicon?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  tenant?: T;
  onboardingWelcomeSeenAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  siteType?: T;
  customDomains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  branding?:
    | T
    | {
        logo?: T;
        favicon?: T;
        primaryColor?: T;
        secondaryColor?: T;
        accentColor?: T;
        displayFont?: T;
      };
  location?:
    | T
    | {
        lat?: T;
        lng?: T;
        timezone?: T;
      };
  prayerCalc?:
    | T
    | {
        method?: T;
        asrMadhab?: T;
      };
  contactInfo?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  footerTagline?: T;
  status?: T;
  trialEndsAt?: T;
  signupMetadata?: T;
  subscriptionPlan?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  currentPeriodEnd?: T;
  gracePeriodEndsAt?: T;
  donationConfig?:
    | T
    | {
        mode?: T;
        externalUrl?: T;
        stripeAccountId?: T;
        stripeAccountConnectedAt?: T;
        stripeChargesEnabled?: T;
        stripePayoutsEnabled?: T;
        stripeAccountLastSyncedAt?: T;
      };
  onboarding?:
    | T
    | {
        branding?: T;
        identity?: T;
        prayer?: T;
        firstEvent?: T;
        hero?: T;
        donations?: T;
      };
  onboardingCompletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null)
      | ({
          relationTo: 'hero-slides';
          value: number | HeroSlide;
        } | null)
      | ({
          relationTo: 'announcements';
          value: number | Announcement;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}